version: '3.5'
services:
  nats-auth:
    image: nats:alpine
    restart: always
    ports:
      - '4222:4222'
    networks: ['nats']
    
  nats-blog:
    image: nats:alpine
    restart: always
    ports:
      - '4223:4223'
    networks: ['nats']

  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: mongo
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  postgres:
    image: postgres
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres
    # volumes:
    #   - ./databases/postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
  nats:
    name: nats
