version: '3.5'
services:
  nats-auth:
    image: nats
    restart: always
    command: '--cluster nats://localhost:4248 --p 4222'
    networks: ['nats']
    ports:
      - '4222:4222'

  nats-blog:
    image: nats
    restart: always
    command: '--cluster nats://localhost:5248 --p 5222'
    networks: ['nats']
    ports:
      - '5222:5222'

  db-blog:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: mongo
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - mongodb_network

  db-auth:
    image: postgres
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: auth
    # volumes:
    #   - ./databases/postgres:/var/lib/postgresql/data

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: db-blog
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
      - mongodb_network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

networks:
  nats:
    name: nats
  mongodb_network:
    driver: bridge
