module.exports = {
  projects: [
    '<rootDir>/packages/plugins/common',
    '<rootDir>/packages/plugins/common-e2e',
    '<rootDir>/packages/plugins/web',
    '<rootDir>/packages/plugins/web-e2e',
    '<rootDir>/packages/plugins/nest',
    '<rootDir>/packages/plugins/nest-e2e',
    '<rootDir>/packages/plugins/angular',
    '<rootDir>/packages/plugins/angular-e2e',
    '<rootDir>/packages/plugins/xplat',
    '<rootDir>/packages/plugins/xplat-e2e',
    '<rootDir>/packages/apps/ng-dep-graph',
    '<rootDir>/packages/apps/deps-graph/interfaces',
    '<rootDir>/packages/apps/deps-graph/eslint',
    '<rootDir>/packages/apps/deps-graph/features',
    '<rootDir>/packages/apps/deps-graph/ui',
    '<rootDir>/packages/apps/deps-graph/data-access',
    '<rootDir>/packages/apps/deps-graph/utils',
    '<rootDir>/packages/packages/angular/material',
    '<rootDir>/packages/webpack',
    '<rootDir>/packages/apps/deps-graph/styles',
  ],
};
